// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI_KpmSjCfAVvxqkOBlnph0MuStemCU48',
    appId: '1:476040549119:web:347a8612e2fe41d49272ca',
    messagingSenderId: '476040549119',
    projectId: 'mynote-haile-flutter',
    authDomain: 'mynote-haile-flutter.firebaseapp.com',
    storageBucket: 'mynote-haile-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEXGC91SOT54WTcE6HDglOJtLOwOaYmkM',
    appId: '1:476040549119:android:cd207dad257e60169272ca',
    messagingSenderId: '476040549119',
    projectId: 'mynote-haile-flutter',
    storageBucket: 'mynote-haile-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt7uTqHlMjWqWdPPyjPiM55eaWWmbJYEk',
    appId: '1:476040549119:ios:b21c7e51b99894459272ca',
    messagingSenderId: '476040549119',
    projectId: 'mynote-haile-flutter',
    storageBucket: 'mynote-haile-flutter.appspot.com',
    iosClientId: '476040549119-v2tsf04hdlbdefkqd0p8ajbmq5ig3n1m.apps.googleusercontent.com',
    iosBundleId: 'com.haile.mynotes',
  );
}
